In [2]:
import pandas as pd

In [72]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

In [73]:
import numpy as np
import pandas as pd

In [74]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [75]:
len(df.index)

2160

In [76]:
df.Brand.nunique()

27

In [77]:
df.isnull().any().sum()

np.int64(3)

In [78]:
df['Final Price'].loc[df['Brand'] == 'Dell'].max()

np.float64(3936.0)

In [79]:
df.Screen.median()

np.float64(15.6)

In [80]:
df.Screen.mode()

0    15.6
Name: Screen, dtype: float64

In [82]:
df.fillna({'Screen' : df.Screen.mode()[0]}, inplace=True)

In [85]:
df.Screen.loc[df.Screen.isnull()]

Series([], Name: Screen, dtype: float64)

In [84]:
df.Screen.mode()

0    15.6
Name: Screen, dtype: float64

In [92]:
df['Brand']=='Innjoo'

0       False
1       False
2       False
3       False
4       False
        ...  
2155    False
2156    False
2157    False
2158    False
2159    False
Name: Brand, Length: 2160, dtype: bool

In [124]:
x = df[['RAM', 'Storage', 'Screen']].loc[df['Brand']=='Innjoo'].to_numpy()
x

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [125]:
xtx = np.matmul(x.transpose(), x)

In [126]:
np.linalg.inv(xtx)

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [137]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [138]:
w = np.matmul(np.matmul(np.linalg.inv(xtx), x.transpose()), y)
w.sum()

np.float64(91.2998806299555)

In [130]:
w = np.matmul(np.linalg.inv(xtx), x.transpose()) * y
w.sum()

np.float64(46.17290588427105)

In [118]:
w = np.matmul(np.matmul(np.linalg.inv(xtx), x.transpose()), y)

In [119]:
w.sum()

np.float64(46.17290588427109)

In [6]:
# creating arrays
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(5, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [13]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
#ND arrays
np.zeros((5,2)) # rows then columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [16]:
np.random.randn(5, 2) # Normal Distribution

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [17]:
np.random.randint(low=0, high=100, size =(5, 2))

array([[83, 31],
       [66, 80],
       [52, 76],
       [50,  4],
       [90, 63]])

In [18]:
a.dot(a)

np.int64(146)

In [20]:
np.random.randint(low=0, high=100, size =(2, 5)).dot(a)

array([1750,  646])

In [27]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [28]:
df = pd.DataFrame(data, columns=columns)

In [24]:
# Can also create via dictionary:
# data = [
#  {
#    "Make": "FORD",
#    "Model": "Sonata"
#  },
#  {}]

In [29]:
df.groupby('Transmission Type').MSRP.min()

Transmission Type
AUTOMATIC    27150
MANUAL        2000
Name: MSRP, dtype: int64